# Generated by Django 3.1.5 on 2021-05-05 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0011_auto_20210504_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data')),
                ('unidades', models.IntegerField(default=1, verbose_name='Unidades Compradas')),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Pago')),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor', verbose_name='Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Material')),
                ('categoria', models.CharField(max_length=150, verbose_name='Categoria')),
                ('subcategoria', models.CharField(blank=True, max_length=150, null=True, verbose_name='Subcategoria')),
                ('qualidade', models.IntegerField(default=0, verbose_name='Qualidade')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Altura')),
                ('largura', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Largura')),
                ('comprimento', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Comprimento')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Unitário')),
                ('unidade_de_medida', models.CharField(blank=True, choices=[('g', 'Gramas'), ('ct', 'Quilates')], max_length=2, null=True, verbose_name='Unidade de Medida')),
                ('unidades', models.IntegerField(blank=True, default=0, null=True, verbose_name='Unidades em Estoque')),
                ('entrada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiais.entrada', verbose_name='Entrada')),
            ],
        ),
    ]
