# Generated by Django 3.1.5 on 2021-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidades',
            field=models.IntegerField(default=0, verbose_name='Unidades em Estoque'),
        ),
    ]
