# Generated by Django 3.1.5 on 2021-05-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_auto_20210505_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='entrada',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiais.entrada', verbose_name='Entrada'),
        ),
    ]
