# Generated by Django 3.1.5 on 2021-05-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0003_auto_20210506_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='materiais', verbose_name='Foto do Material'),
        ),
    ]
