# Generated by Django 3.1.5 on 2021-05-17 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0013_auto_20210515_1915'),
        ('materiais', '0004_material_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='unidades',
            new_name='estoque',
        ),
        migrations.AddField(
            model_name='material',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor', verbose_name='Fornecedor'),
        ),
        migrations.AddField(
            model_name='material',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Pago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='unidades_compradas',
            field=models.IntegerField(default=1, verbose_name='Unidades Compradas'),
        ),
        migrations.AlterField(
            model_name='material',
            name='entrada',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Entrada'),
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
