# Generated by Django 3.1.5 on 2021-05-17 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0013_auto_20210515_1915'),
        ('materiais', '0005_auto_20210517_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
