# Generated by Django 3.1.5 on 2021-05-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_auto_20210517_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unidade_de_medida',
            field=models.CharField(blank=True, choices=[('', 'Uniade de Medida'), ('g', 'Gramas'), ('ct', 'Quilates')], max_length=2, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
