# Generated by Django 3.1.5 on 2021-05-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0007_auto_20210522_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
