# Generated by Django 3.1.5 on 2021-06-10 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_auto_20210530_1434'),
        ('materiais', '0008_material_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='despesa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.despesa', verbose_name='Despesa'),
        ),
    ]
