# Generated by Django 3.1.5 on 2021-06-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0010_auto_20210611_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='total_pago',
            new_name='valor',
        ),
    ]
