# Generated by Django 3.1.5 on 2021-07-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0011_auto_20210614_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo_do_fornecedor',
            field=models.CharField(blank=True, help_text='Código do produto utilizado pelo fornecedor.', max_length=50, null=True, verbose_name='Código do Fornecedor'),
        ),
    ]
