# Generated by Django 3.1.5 on 2021-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_auto_20210705_1634'),
        ('materiais', '0012_material_codigo_do_fornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='despesa',
        ),
        migrations.AddField(
            model_name='material',
            name='despesas',
            field=models.ManyToManyField(blank=True, to='financeiro.Despesa', verbose_name='Despesas'),
        ),
    ]
