# Generated by Django 3.1.5 on 2021-07-29 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_auto_20210705_1634'),
        ('fornecedores', '0021_auto_20210616_1523'),
        ('materiais', '0013_auto_20210717_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='codigo_do_fornecedor',
        ),
        migrations.RemoveField(
            model_name='material',
            name='despesas',
        ),
        migrations.RemoveField(
            model_name='material',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='material',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unidades_compradas',
        ),
        migrations.RemoveField(
            model_name='material',
            name='valor',
        ),
        migrations.AlterField(
            model_name='material',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='altura'),
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.CharField(max_length=150, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='material',
            name='comprimento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='comprimento'),
        ),
        migrations.AlterField(
            model_name='material',
            name='estoque',
            field=models.IntegerField(blank=True, default=0, verbose_name='unidades em estoque'),
        ),
        migrations.AlterField(
            model_name='material',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='materiais', verbose_name='foto do material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='largura'),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='nome do material'),
        ),
        migrations.AlterField(
            model_name='material',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='material',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='peso total'),
        ),
        migrations.AlterField(
            model_name='material',
            name='qualidade',
            field=models.IntegerField(blank=True, default=1, verbose_name='qualidade'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='subcategoria'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unidade_de_medida',
            field=models.CharField(blank=True, choices=[('', 'Uniade de Medida'), ('g', 'Gramas'), ('ct', 'Quilates')], max_length=2, null=True, verbose_name='unidade de medida'),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('codigo_do_fornecedor', models.CharField(blank=True, help_text='Código do produto utilizado pelo fornecedor.', max_length=50, null=True, verbose_name='código do fornecedor')),
                ('unidades_compradas', models.IntegerField(default=1, verbose_name='unidades compradas')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='peso total')),
                ('unidade_de_medida', models.CharField(blank=True, choices=[('', 'Uniade de Medida'), ('g', 'Gramas'), ('ct', 'Quilates')], max_length=2, null=True, verbose_name='unidade de medida')),
                ('despesa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.despesa', verbose_name='despesa')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fornecedores.fornecedor', verbose_name='fornecedor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.material', verbose_name='material')),
            ],
        ),
    ]
