# Generated by Django 3.1.5 on 2021-07-29 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_auto_20210705_1634'),
        ('materiais', '0014_auto_20210729_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='valor total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='codigo_do_fornecedor',
            field=models.CharField(blank=True, help_text='Código utilizado pelo fornecedor para identificar este produto.', max_length=50, null=True, verbose_name='código do fornecedor'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.despesa', verbose_name='despesa'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='peso total'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='unidade_de_medida',
            field=models.CharField(choices=[('', 'Uniade de Medida'), ('g', 'Gramas'), ('ct', 'Quilates')], max_length=2, verbose_name='unidade de medida'),
        ),
    ]
