# Generated by Django 3.1.5 on 2021-07-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0015_auto_20210729_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='unidades_compradas',
            new_name='unidades',
        ),
    ]
