# Generated by Django 3.1.5 on 2021-07-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_auto_20210705_1634'),
        ('materiais', '0016_auto_20210729_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrada',
            options={'get_latest_by': 'data'},
        ),
        migrations.AlterField(
            model_name='entrada',
            name='despesa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.despesa', verbose_name='despesa'),
        ),
    ]
