# Generated by Django 3.1.5 on 2021-08-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0025_auto_20210705_1634'),
        ('materiais', '0017_auto_20210729_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='despesa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.despesa', verbose_name='despesa'),
        ),
    ]
