# Generated by Django 3.2.8 on 2021-10-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0019_auto_20211006_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='peso total'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='unidade_de_medida',
            field=models.CharField(blank=True, choices=[('', 'Uniade de Medida'), ('g', 'Gramas'), ('ct', 'Quilates')], max_length=2, null=True, verbose_name='unidade de medida'),
        ),
    ]
