# Generated by Django 3.2.8 on 2021-10-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0021_auto_20211031_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='peso total'),
        ),
    ]
