# Generated by Django 4.0.2 on 2022-03-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0025_alter_entrada_alterar_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='alterar_estoque',
            field=models.BooleanField(default=True, help_text='Define se o peso e as unidades desta entrada devem ser adicionados ao estoque.', verbose_name='alterar estoque'),
        ),
    ]
