# Generated by Django 4.0.2 on 2022-03-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0026_alter_entrada_alterar_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='peso total'),
        ),
    ]
