# Generated by Django 3.1.5 on 2021-04-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products', verbose_name='Foto do Produto')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('colecao', models.CharField(max_length=150, verbose_name='Coleção')),
                ('familia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Família')),
                ('data_criacao', models.DateField(blank=True, null=True, verbose_name='Data de Criação')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Unidades')),
                ('tamanho', models.IntegerField(blank=True, null=True, verbose_name='Tamanho')),
                ('categorias', models.ManyToManyField(to='produtos.Categoria', verbose_name='Categorias')),
            ],
        ),
    ]
