# Generated by Django 3.1.5 on 2021-04-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='produtos/default.jpg', null=True, upload_to='produtos', verbose_name='Foto do Produto'),
        ),
    ]
