# Generated by Django 3.1.5 on 2021-04-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='unidades',
            field=models.IntegerField(default=0, verbose_name='Unidades em Estoque'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='produtos/default.jpg', null=True, upload_to='produtos', verbose_name='Foto do Produto'),
        ),
    ]
