# Generated by Django 3.1.5 on 2021-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20210430_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='produtos', verbose_name='Foto do Produto'),
        ),
    ]
