# Generated by Django 3.1.5 on 2021-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0011_auto_20210504_1711'),
        ('produtos', '0004_auto_20210503_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='servicos',
            field=models.ManyToManyField(blank=True, to='fornecedores.Servico', verbose_name='Serviços'),
        ),
    ]
