# Generated by Django 3.1.5 on 2021-05-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_material_foto'),
        ('produtos', '0005_produto_servicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.IntegerField(default=1, verbose_name='Unidades Compradas')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Unitário')),
                ('unidade_de_medida', models.CharField(blank=True, choices=[('g', 'Gramas'), ('ct', 'Quilates')], max_length=2, null=True, verbose_name='Unidade de Medida')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiais.material', verbose_name='Material')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='materiais',
            field=models.ManyToManyField(blank=True, to='produtos.MaterialDoProduto', verbose_name='Materiais'),
        ),
    ]
