# Generated by Django 3.1.5 on 2021-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20210508_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='observacao',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Observação'),
        ),
    ]
