# Generated by Django 3.1.5 on 2021-05-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20210524_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdoproduto',
            name='unidade_de_medida',
            field=models.CharField(blank=True, choices=[('', 'Unidade de Medida'), ('g', 'Gramas'), ('ct', 'Quilates')], max_length=2, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
