# Generated by Django 3.2.8 on 2022-01-08 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0012_alter_produto_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Criação'),
        ),
    ]
