# Generated by Django 3.2.8 on 2022-01-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0014_alter_produto_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
