# Generated by Django 4.0.2 on 2022-03-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_remove_produto_servicos_servicodoproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='materiais',
        ),
        migrations.AddField(
            model_name='materialdoproduto',
            name='produto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicodoproduto',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='servicodoproduto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor'),
        ),
    ]
