# Generated by Django 4.0.2 on 2022-03-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0016_remove_produto_servicos_servicodoproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='servicos',
        ),
        migrations.AddField(
            model_name='materialdoproduto',
            name='produto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='produto', null=True),
            preserve_default=False,
        ),
    ]
