# Generated by Django 4.0.2 on 2022-03-24 18:23

from django.db import migrations

def load_product_materials_details(apps, schema_editor):
    MaterialDoProduto = apps.get_model('produtos', 'MaterialDoProduto')
    Produto = apps.get_model('produtos', 'Produto')
    
    from django.db import connection
    cursor = connection.cursor()
    cursor.execute('''SELECT materialdoproduto_id, produto_id FROM produtos_produto_materiais''')
    materiais = cursor.fetchall()
    
    for material in materiais:
        material_dp = MaterialDoProduto.objects.get(pk=material[0])
        material_dp.produto = Produto.objects.get(pk=material[1])
        material_dp.save()

class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0017_remove_produto_materiais_materialdoproduto_produto_and_more'),
    ]

    operations = [
        migrations.RunPython(load_product_materials_details),
    ]
