# Generated by Django 4.0.2 on 2022-03-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0018_alter_materialdoproduto_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='materiais',
        ),
        migrations.AlterField(
            model_name='materialdoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='produto'),
        ),
    ]
