# Generated by Django 4.0.4 on 2022-09-13 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_produto_barcode_alter_produto_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='unidades',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='unidades em estoque'),
        ),
    ]
