# Generated by Django 4.0.4 on 2022-05-17 18:33

from django.db import migrations

def generate_produto_barcodes(apps, schema_editor):
    Produto = apps.get_model('produtos', 'Produto')

    from django.db import connection
    cursor = connection.cursor()
    cursor.execute('''SELECT id FROM produtos_produto''')
    produtos = cursor.fetchall()
    
    for p in produtos:
        produto = Produto.objects.get(pk=p[0])
        produto.generate_barcode()

class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_produto_barcode_alter_produto_tamanho_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_produto_barcodes),
    ]
