# Generated by Django 3.1.5 on 2021-05-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0010_auto_20210527_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('parcelas', models.IntegerField(choices=[(1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x'), (7, '7x'), (8, '8x'), (9, '9x'), (10, '10x'), (11, '11x'), (12, '12x')], default=1, verbose_name='Parcelas')),
                ('ultima_parcela', models.DateField(blank=True, null=True, verbose_name='Última Parcela')),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Pago')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.cliente', verbose_name='Cliente')),
                ('produtos', models.ManyToManyField(to='produtos.Produto', verbose_name='Produtos')),
            ],
            options={
                'get_latest_by': 'data',
            },
        ),
    ]
