# Generated by Django 3.1.5 on 2021-05-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='total_pago',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='ultima_parcela',
        ),
        migrations.AddField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Total'),
            preserve_default=False,
        ),
    ]
