# Generated by Django 3.1.5 on 2021-05-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_auto_20210530_1434'),
        ('vendas', '0002_auto_20210528_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='receita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.receita', verbose_name='Receita'),
        ),
    ]
