# Generated by Django 4.0.4 on 2022-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20211006_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de aniversário'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
    ]
