# Generated by Django 4.0.4 on 2022-07-01 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0027_remove_despesa_encerrada'),
        ('produtos', '0020_produto_barcode_alter_produto_tamanho_and_more'),
        ('vendas', '0005_cliente_birth_date_cliente_cpf_cliente_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='nome')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.markup', verbose_name='mark up')),
                ('is_active', models.BooleanField(default=True, verbose_name='está ativo')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.basket', verbose_name='carrinho de compras')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='produto')),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='basket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.basket', verbose_name='basket'),
            preserve_default=False,
        ),
    ]
