# Generated by Django 4.0.4 on 2022-06-21 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0020_produto_barcode_alter_produto_tamanho_and_more'),
        ('vendas', '0005_cliente_birth_date_cliente_cpf_cliente_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='está ativo')),
                ('markup', models.FloatField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantidade')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.basket', verbose_name='carrinho de compras')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto', verbose_name='produto')),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.basket', verbose_name='Cliente'),
        ),
    ]
