# Generated by Django 4.0.4 on 2022-06-09 20:10

from django.db import migrations, models


def create_basket_for_existing_sales(apps, schema_editor):
    Produto = apps.get_model('produtos', 'Produto')
    Venda = apps.get_model('vendas', 'Venda')
    Basket = apps.get_model('vendas', 'Basket')
    BasketItem = apps.get_model('vendas', 'BasketItem')
    
    from django.db import connection
    cursor = connection.cursor()
    cursor.execute('''SELECT id FROM vendas_venda''')
    vendas = cursor.fetchall()
    
    for venda in vendas:
        venda = Venda.objects.get(pk=venda[0])
        basket = Basket.objects.create(is_active=False)
        cursor.execute(f'''SELECT produto_id FROM vendas_venda_produtos WHERE venda_id = {venda.id}''')
        produtos = cursor.fetchall()
        for p in produtos:
            produto = Produto.objects.get(pk=p[0])
            BasketItem.objects.create(basket=basket, product=produto, quantity=1)
        venda.basket = basket
        venda.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_create_basket_basket_item_and_more'),
    ]

    operations = [
        migrations.RunPython(create_basket_for_existing_sales),
    ]
