# Generated by Django 4.0.4 on 2022-06-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_basket_remove_venda_produtos_basketitem_venda_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantidade'),
        ),
    ]
