# Generated by Django 4.0.4 on 2022-07-01 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_create_basket_for_existing_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.cliente', verbose_name='cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='observação'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='parcelas',
            field=models.IntegerField(choices=[(1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x'), (7, '7x'), (8, '8x'), (9, '9x'), (10, '10x'), (11, '11x'), (12, '12x')], default=1, verbose_name='parcelas'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='receita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.receita', verbose_name='receita'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='valor'),
        ),
        migrations.AddField(
            model_name='venda',
            name='basket',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='vendas.basket', verbose_name='basket'),
            preserve_default=False,
        ),
    ]
