# Generated by Django 4.0.4 on 2022-07-03 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_remove_venda_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markup',
            name='value',
            field=models.FloatField(verbose_name='valor'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='data'),
        ),
    ]
