# Generated by Django 4.0.4 on 2022-07-04 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_alter_basketitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='basket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.basket', verbose_name='basket'),
        ),
    ]
