# Generated by Django 3.1.5 on 2021-05-08 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('categoria', models.CharField(max_length=150, verbose_name='Categoria')),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('repetir', models.CharField(choices=[('n', 'Nunca'), ('s', 'Semanalmente'), ('q', 'Quinzenalmente'), ('m', 'Mensalmente'), ('b', 'Bimestralmente'), ('t', 'Trimestralmente'), ('a', 'Anualmente')], max_length=1, verbose_name='Repetir')),
            ],
            options={
                'get_latest_by': 'data',
            },
        ),
    ]
