# Generated by Django 3.1.5 on 2021-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20210508_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Pago'),
            preserve_default=False,
        ),
    ]
