# Generated by Django 3.1.5 on 2021-05-11 19:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_venda_total_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'get_latest_by': 'data'},
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('categoria', models.CharField(max_length=150, verbose_name='Categoria')),
                ('parcela', models.IntegerField(verbose_name='Parcela')),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.venda', verbose_name='Venda')),
            ],
        ),
    ]
