# Generated by Django 3.1.5 on 2021-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_auto_20210511_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='repetir',
            field=models.CharField(choices=[('n', 'Nunca'), ('d', 'Diariamente'), ('m', 'Mensalmente'), ('a', 'Anualmente')], max_length=1, verbose_name='Repetir'),
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
