# Generated by Django 3.1.5 on 2021-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20210514_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='ultima_parcela',
            field=models.DateField(blank=True, null=True, verbose_name='Última Parcela'),
        ),
    ]
