# Generated by Django 3.1.5 on 2021-05-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_auto_20210514_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
