# Generated by Django 3.1.5 on 2021-05-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_auto_20210514_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
    ]
