# Generated by Django 3.1.5 on 2021-05-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_auto_20210514_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='repetir',
            field=models.CharField(choices=[('n', 'Nunca'), ('m', 'Mensalmente'), ('a', 'Anualmente')], max_length=1, verbose_name='Repetir'),
        ),
    ]
