# Generated by Django 3.1.5 on 2021-05-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_auto_20210520_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='total_pago',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='categoria',
        ),
        migrations.AddField(
            model_name='despesa',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Variável usada para interromper despesas com repetição.', verbose_name='Despesa ativa'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='nome',
            field=models.CharField(default=0, max_length=150, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='repetir',
            field=models.CharField(choices=[('', 'Nunca'), ('m', 'Mensalmente'), ('a', 'Anualmente')], max_length=1, verbose_name='Repetir'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
