# Generated by Django 3.1.5 on 2021-05-27 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_auto_20210527_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('categoria', models.CharField(max_length=150, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
            ],
            options={
                'get_latest_by': 'data',
            },
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='nome',
        ),
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(default=None, max_length=150, verbose_name='Categoria'),
            preserve_default=False,
        ),
    ]
