# Generated by Django 3.1.5 on 2021-05-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_auto_20210528_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='data_de_encerramento',
            field=models.DateField(blank=True, help_text='Data de pagamento da última parcela.', null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AddField(
            model_name='receita',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Variável usada para verificar o se ainda existem percelas a serem pagas.', verbose_name='Receita ativa'),
        ),
    ]
