# Generated by Django 3.1.5 on 2021-05-30 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_auto_20210528_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='parcelas',
        ),
        migrations.AddField(
            model_name='parcela',
            name='receita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financeiro.receita', verbose_name='Receita'),
            preserve_default=False,
        ),
    ]
