# Generated by Django 3.1.5 on 2021-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_auto_20210530_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='repetir',
            field=models.CharField(blank=True, choices=[('', 'Nunca'), ('m', 'Mensalmente'), ('a', 'Anualmente')], default='', max_length=1, null=True, verbose_name='Repetir'),
        ),
    ]
