# Generated by Django 3.1.5 on 2021-07-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0023_auto_20210616_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='is_active',
        ),
        migrations.AddField(
            model_name='despesa',
            name='encerrada',
            field=models.BooleanField(default=True, help_text='Utilizada para interromper despesas com repetição.', verbose_name='Encerrada'),
        ),
    ]
