# Generated by Django 4.0.1 on 2022-02-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0026_auto_20211006_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='encerrada',
        ),
    ]
