# Generated by Django 3.1.5 on 2021-05-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Endereço de Email')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Serviços ou produtos fornecidos', max_length=150, verbose_name='Fornecimento')),
                ('qualidade', models.IntegerField(default=0, verbose_name='Qualidade')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('cep', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.PositiveBigIntegerField(unique=True, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefones', models.PositiveBigIntegerField(verbose_name='Telefone')),
                ('localizacoes', models.CharField(max_length=150, verbose_name='País')),
                ('fornecimento', models.CharField(max_length=150, verbose_name='Fornecimento')),
                ('emails', models.ManyToManyField(to='fornecedores.Email', verbose_name='Endereço de Email')),
            ],
        ),
    ]
