# Generated by Django 3.1.5 on 2021-05-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='emails',
            field=models.ManyToManyField(blank=True, to='fornecedores.Email', verbose_name='Endereços de Email'),
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='fornecimento',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='fornecimento',
            field=models.ManyToManyField(blank=True, to='fornecedores.Fornecimento', verbose_name='Fornecimentos'),
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='localizacoes',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='localizacoes',
            field=models.ManyToManyField(blank=True, to='fornecedores.Local', verbose_name='Localizações'),
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefones',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefones',
            field=models.ManyToManyField(blank=True, to='fornecedores.Telefone', verbose_name='Telefones'),
        ),
    ]
