# Generated by Django 3.1.5 on 2021-05-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_auto_20210430_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='foto',
            field=models.ImageField(blank=True, default='fornecedores/default.jpg', null=True, upload_to='fornecedores', verbose_name='Foto do Fornecedor'),
        ),
    ]
