# Generated by Django 3.1.5 on 2021-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_fornecedor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='fornecedores', verbose_name='Foto do Fornecedor'),
        ),
    ]
