# Generated by Django 3.1.5 on 2021-05-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_auto_20210501_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='cep',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CEP'),
        ),
    ]
