# Generated by Django 3.1.5 on 2021-05-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0005_auto_20210501_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='telefone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefone'),
        ),
    ]
