# Generated by Django 3.1.5 on 2021-05-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0006_auto_20210501_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(blank=True, help_text='Digite o CNPJ ou IE do fornecedor.', max_length=20, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='fornecimento',
            name='nome',
            field=models.CharField(help_text='Serviços ou produtos fornecidos.', max_length=150, verbose_name='Fornecimento'),
        ),
    ]
