# Generated by Django 3.1.5 on 2021-05-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0008_auto_20210503_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosbancarios',
            old_name='branch',
            new_name='agencia',
        ),
        migrations.RenameField(
            model_name='dadosbancarios',
            old_name='bank',
            new_name='banco',
        ),
        migrations.RenameField(
            model_name='dadosbancarios',
            old_name='number',
            new_name='numero',
        ),
        migrations.AlterField(
            model_name='dadosbancarios',
            name='tipo_de_transacao',
            field=models.CharField(choices=[('cc', 'Conta Corrente'), ('px', 'Pix')], max_length=2, verbose_name='Tipo de Transação'),
        ),
    ]
