# Generated by Django 3.1.5 on 2021-05-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0011_auto_20210504_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, verbose_name='Número')),
            ],
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='documento',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='documentos',
            field=models.ManyToManyField(blank=True, to='fornecedores.Documento', verbose_name='Documentos'),
        ),
    ]
