# Generated by Django 3.1.5 on 2021-05-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0012_auto_20210515_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='documento',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='documento',
            name='nome',
            field=models.CharField(default=1, help_text='Exemplos: CNPJ, IE', max_length=20, verbose_name='Documento'),
            preserve_default=False,
        ),
    ]
