# Generated by Django 3.1.5 on 2021-05-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0013_auto_20210515_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='foto',
        ),
    ]
