# Generated by Django 3.1.5 on 2021-05-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0015_auto_20210520_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor', verbose_name='Fornecedor'),
            preserve_default=False,
        ),
    ]
