# Generated by Django 3.1.5 on 2021-05-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0016_documento_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='tipo_de_transacao',
            field=models.CharField(choices=[('', 'Tipo de Transação'), ('cc', 'Conta Corrente'), ('px', 'Pix')], max_length=2, verbose_name='Tipo de Transação'),
        ),
    ]
