# Generated by Django 3.1.5 on 2021-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0017_auto_20210520_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='tipo_de_transacao',
            field=models.CharField(choices=[('', 'Tipo de Transação'), ('dp', 'Depósito'), ('px', 'Pix')], max_length=2, verbose_name='Tipo de Transação'),
        ),
    ]
