# Generated by Django 3.1.5 on 2021-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0018_auto_20210524_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecimento',
            name='qualidade',
            field=models.IntegerField(null=True, verbose_name='Qualidade'),
        ),
    ]
