# Generated by Django 3.2.8 on 2021-10-31 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0022_auto_20211006_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecimento',
            name='qualidade',
        ),
    ]
